# Generated by Django 2.2.2 on 2019-11-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191106_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrecord',
            name='habit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='habit_record_is_for', to='core.Habit'),
            preserve_default=False,
        ),
    ]
