# Generated by Django 2.2.2 on 2019-11-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_habitrecord_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitobserver',
            name='habit_observing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habbit_record_observing', to='core.Habit'),
        ),
    ]
