# Generated by Django 2.2.7 on 2019-11-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191106_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='actual_num_achieved',
            field=models.IntegerField(default=None),
        ),
    ]
